name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie Kodu
        uses: actions/checkout@v2

      - name: Budowanie Obrazu Docker dla Frontendu
        run: |
          cd front-tsx
          docker image build -t teatrocamillo/front-tsx:v0 .

      - name: Wysyłanie Obrazu Docker Frontendu do DockerHub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push teatrocamillo/front-tsx:v0

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie Kodu
        uses: actions/checkout@v2

      - name: Budowanie Obrazu Docker dla Backend
        run: |
          cd task-echo
          docker image build -t teatrocamillo/task-echo:v0 .

      - name: Wysyłanie Obrazu Docker Backend do DockerHub
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push teatrocamillo/task-echo:v0

